### ISSUE TITLE
contact info

### ISSUE THREAD

**Issue by kislyuk** [czi/tc4-shield#1]
Hi, I'm trying to get in touch with the owner of this account @czi, could you indicate a means to contact you? Thanks.

**Comment by czi** [comment]
Hi, What can I do for you? RE: @czi on Github.

**Comment by kislyuk** [comment]
Hi, thanks for the reply. I'm looking to register an organization account
with the same name as your github user handle. I noticed that you haven't
been using your account for a while (at least not in public), so I was
wondering if you would be OK with renaming your account. You can do so
under "Change Username" in https://github.com/settings/admin. Thanks for
your consideration.

**Comment by czi** [comment]
Not interested in giving up my user account.  This is based on my name.
Sorry.

**Comment by kislyuk** [comment]
OK, understood, thanks again.
